// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: coffee_shop.proto

package coffee_shop_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_coffee_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_coffee_shop_proto_rawDescGZIP(), []int{0}
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Items               `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_coffee_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_coffee_shop_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetItem() []*Items {
	if x != nil {
		return x.Item
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_coffee_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_coffee_shop_proto_rawDescGZIP(), []int{2}
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Items               `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_coffee_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_coffee_shop_proto_rawDescGZIP(), []int{3}
}

func (x *Menu) GetItem() []*Items {
	if x != nil {
		return x.Item
	}
	return nil
}

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_coffee_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_coffee_shop_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_coffee_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_coffee_shop_proto_rawDescGZIP(), []int{5}
}

func (x *Items) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Items) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_coffee_shop_proto protoreflect.FileDescriptor

const file_coffee_shop_proto_rawDesc = "" +
	"\n" +
	"\x11coffee_shop.proto\x12\n" +
	"coffeeshop\"\r\n" +
	"\vMenuRequest\"0\n" +
	"\aReceipt\x12%\n" +
	"\x04item\x18\x01 \x03(\v2\x11.coffeeshop.ItemsR\x04item\"\a\n" +
	"\x05Order\"-\n" +
	"\x04Menu\x12%\n" +
	"\x04item\x18\x01 \x03(\v2\x11.coffeeshop.ItemsR\x04item\"@\n" +
	"\vOrderStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\x05Items\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xc0\x01\n" +
	"\n" +
	"CoffeeShop\x128\n" +
	"\aGetMenu\x12\x17.coffeeshop.MenuRequest\x1a\x10.coffeeshop.Menu\"\x000\x01\x126\n" +
	"\n" +
	"PlaceOrder\x12\x11.coffeeshop.Order\x1a\x13.coffeeshop.Receipt\"\x00\x12@\n" +
	"\x0eGetOrderStatus\x12\x13.coffeeshop.Receipt\x1a\x17.coffeeshop.OrderStatus\"\x00B<Z:github.com/wycliff-ochieng/proto-project/coffee_shop.protob\x06proto3"

var (
	file_coffee_shop_proto_rawDescOnce sync.Once
	file_coffee_shop_proto_rawDescData []byte
)

func file_coffee_shop_proto_rawDescGZIP() []byte {
	file_coffee_shop_proto_rawDescOnce.Do(func() {
		file_coffee_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coffee_shop_proto_rawDesc), len(file_coffee_shop_proto_rawDesc)))
	})
	return file_coffee_shop_proto_rawDescData
}

var file_coffee_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coffee_shop_proto_goTypes = []any{
	(*MenuRequest)(nil), // 0: coffeeshop.MenuRequest
	(*Receipt)(nil),     // 1: coffeeshop.Receipt
	(*Order)(nil),       // 2: coffeeshop.Order
	(*Menu)(nil),        // 3: coffeeshop.Menu
	(*OrderStatus)(nil), // 4: coffeeshop.OrderStatus
	(*Items)(nil),       // 5: coffeeshop.Items
}
var file_coffee_shop_proto_depIdxs = []int32{
	5, // 0: coffeeshop.Receipt.item:type_name -> coffeeshop.Items
	5, // 1: coffeeshop.Menu.item:type_name -> coffeeshop.Items
	0, // 2: coffeeshop.CoffeeShop.GetMenu:input_type -> coffeeshop.MenuRequest
	2, // 3: coffeeshop.CoffeeShop.PlaceOrder:input_type -> coffeeshop.Order
	1, // 4: coffeeshop.CoffeeShop.GetOrderStatus:input_type -> coffeeshop.Receipt
	3, // 5: coffeeshop.CoffeeShop.GetMenu:output_type -> coffeeshop.Menu
	1, // 6: coffeeshop.CoffeeShop.PlaceOrder:output_type -> coffeeshop.Receipt
	4, // 7: coffeeshop.CoffeeShop.GetOrderStatus:output_type -> coffeeshop.OrderStatus
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coffee_shop_proto_init() }
func file_coffee_shop_proto_init() {
	if File_coffee_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coffee_shop_proto_rawDesc), len(file_coffee_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coffee_shop_proto_goTypes,
		DependencyIndexes: file_coffee_shop_proto_depIdxs,
		MessageInfos:      file_coffee_shop_proto_msgTypes,
	}.Build()
	File_coffee_shop_proto = out.File
	file_coffee_shop_proto_goTypes = nil
	file_coffee_shop_proto_depIdxs = nil
}
